added comments functionality to blog
rob32/dev-case pull request #2
Opened 2022-07-16 17:01 UTC by alexdeathway

+class based detail post view
+comment functional
-function based detail post view

2022-07-16 19:13 UTC, rob32 commented
Thank you very much for your contribution. Looks pretty good :+1: I will test it locally and merge it afterwards

2022-07-17 15:25 UTC, rob32 requested changes
Here is what I noticed:

- Comments are immediately visible even if `public` is `false`. Default is `false` (should be visible only after checking in admin).
- Submit-Button should be under the Message text field (like on the Contact page)
- Comments are on the far left (should be also "centered").
- "commented" in the user name can be omitted. Looks better with multiple comments.

![pr-screenshot-comments-form](https://user-images.githubusercontent.com/49953458/179405142-15d46fc0-7cf1-4d30-9f27-bee702dec4fe.png)

Thank you again for your contribution. Let me know if I can help or if you have any questions.

2022-07-17 15:25 UTC, rob32 commented on blog/forms.py
> +        labels = {"email": "Your email:"}
display `Name:` instead of "Author" (via labels) would be great. Looks and sounds better?

2022-07-17 15:25 UTC, rob32 commented on blog/migrations/0002_comment_email_alter_comment_message.py
> +            field=models.TextField(max_length=120, verbose_name='Message'),
Strange that here is  `max_lenght` of **120**. In the models.py it is 420. **500** characters would be great here (in blog/models.py)

2022-07-17 15:25 UTC, rob32 commented on templates/blog/blog_detail.html
> +
a second main tag is not necessary

2022-07-17 15:25 UTC, rob32 commented on templates/blog/blog_detail.html
> +      <button type="submit" value="Submit">Submit</button>
a `<br>` would push the button to the right place.
example: `<br><button type="submit" value="Submit">Submit</button>`

2022-07-17 15:25 UTC, rob32 commented on templates/blog/blog_detail.html
> +  </div>
```html
  <div class="small-container margin-bottom">
    <h2 class="main-headline text-center">comments</h2>
    <div>
      {% for comment in comments %}
      <h5 class="lead no-margin-bottom">{{comment.author}}:</h5>
      <p>{{comment.message}}</p>
      {% endfor %}
    </div>
  </div>
```
this with the _from-block_ together inside the main tag would work

2022-07-17 17:51 UTC, alexdeathway commented
the fronted part was just for the prototype to check if that part(comment) is working as expected, will look into the backend issue asap.

2022-08-11 17:46 UTC, rob32 commented
Hey, thanks again for your contribution :green_heart: 

I have implemented the comment-system with captchas in the meantime  [#50e38f5f44d3695751d8e9e6fc8f70aa8756e4b3](https://github.com/rob32/dev-case/commit/50e38f5f44d3695751d8e9e6fc8f70aa8756e4b3)

2022-08-11 17:46 UTC, closed without merging